version: '2'

services:
  mariadb:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
      MYSQL_USER: blue
      MYSQL_PASSWORD: blue
    volumes:
      - ../sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
